--01.FETCH FIRST_NAME,LAST_NAME,SALARY
SET SERVEROUTPUT ON
DECLARE
 CURSOR EMP_CONTEXT 
 IS
  SELECT FIRST_NAME,LAST_NAME,SALARY
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID=&DID;
BEGIN
 FOR I IN EMP_CONTEXT
 LOOP
  DBMS_OUTPUT.PUT_LINE(I.FIRST_NAME||' '||I.LAST_NAME||' '||I.SALARY);
 END LOOP;
END;


--============================================================================
--02.FIND MANAGER NAME AND HOW MANY EMPLOYEES WORKING UDER THAT MANAGER
SET SERVEROUTPUT ON
DECLARE
 CURSOR EMP_CONTEXT
 IS
 SELECT 
 E.FIRST_NAME AS MANAGER_NAME,
 COUNT(*) AS CNT 
 FROM EMPLOYEES E JOIN EMPLOYEES M
 ON(E.EMPLOYEE_ID=M.MANAGER_ID)
 GROUP BY E.FIRST_NAME;
BEGIN
    FOR I IN EMP_CONTEXT 
    LOOP
      DBMS_OUTPUT.PUT_LINE(I.MANAGER_NAME||' '||I.CNT);
    END LOOP;
END;
--=============================================================================
--03.FETCH FIRST_NAME,LAST_NAME,DEPARTMENT_NAME,COUNT 
SET SERVEROUTPUT ON
DECLARE
 CURSOR EMP_CONTEXT 
 IS
  SELECT 
  D.DEPARTMENT_NAME,
  COUNT(E.EMPLOYEE_ID) AS CNT
  FROM EMPLOYEES E JOIN DEPARTMENTS D
  ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
  GROUP BY D.DEPARTMENT_NAME
  ORDER BY COUNT(E.EMPLOYEE_ID) DESC ;
  
BEGIN
  FOR I IN EMP_CONTEXT 
  LOOP
  DBMS_OUTPUT.PUT_LINE(I.DEPARTMENT_NAME||' '||I.CNT);
  END LOOP;
END;

--=======================================================================================
--04.DEPARTMENT WISE TOP 3 SALARIES
SET SERVEROUTPUT ON
DECLARE
  CURSOR EMP_CONTEXT 
  IS
  
  SELECT *FROM(
  SELECT 
  D.DEPARTMENT_NAME,
  E.SALARY,
  DENSE_RANK() OVER(PARTITION BY D.DEPARTMENT_NAME ORDER BY E.SALARY) AS DEN
  FROM EMPLOYEES E JOIN DEPARTMENTS D
  ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
  )WHERE DEN<4;

BEGIN
FOR I IN EMP_CONTEXT 
LOOP
 DBMS_OUTPUT.PUT_LINE(I.DEPARTMENT_NAME||' '||I.SALARY);
END LOOP;
END;


--==============================================================================
--05.FETCH  TOP 3 rd DEPARTMENT WISE  
SET SERVEROUTPUT ON
DECLARE
    CURSOR EMP_CONTEXT 
    IS
    SELECT *FROM(
    SELECT 
    E.FIRST_NAME,
    D.DEPARTMENT_NAME,
    E.SALARY,
    DENSE_RANK() OVER(PARTITION BY D.DEPARTMENT_NAME ORDER BY SALARY DESC) AS DEN
    FROM EMPLOYEES E JOIN DEPARTMENTS D
    ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
    )WHERE DEN=3;
    
BEGIN
 FOR I IN EMP_CONTEXT 
 LOOP
  DBMS_OUTPUT.PUT_LINE(I.FIRST_NAME||' '||I.DEPARTMENT_NAME||' '||I.SALARY||' '||I.DEN);
 END LOOP;
END;

--====================================================================
--06.FETCH FIRST_NAME,EXPER, TOP 2ND SALARY FROM EMPLOYEES TABLE
SET SERVEROUTPUT ON
DECLARE
 CURSOR EMP_CONTEXT 
 IS
 SELECT 
 E.FIRST_NAME AS FNAME,
 D.DEPARTMENT_NAME,
 ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,0) AS TOTAL_EXP,
 DENSE_RANK() OVER(ORDER BY E.SALARY DESC) AS DEN
 FROM EMPLOYEES E JOIN DEPARTMENTS D 
 ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID);
BEGIN
 FOR I IN EMP_CONTEXT
 LOOP
   DBMS_OUTPUT.PUT_LINE(I.FNAME||' '||I.DEPARTMENT_NAME||' '||I.TOTAL_EXP);
 END LOOP;
END;

--=====================================================================================
--FETCH FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_NAME,CITY,POSTAL_CODE,COUTRY_NAME
SET SERVEROUTPUT ON
DECLARE
 CURSOR  EMP_CONTEXT
 IS
 SELECT 
 E.FIRST_NAME,
 E.LAST_NAME,
 E.SALARY,
 D.DEPARTMENT_NAME,
 L.CITY,
 L.POSTAL_CODE,
 C.COUNTRY_NAME
 FROM EMPLOYEES E JOIN DEPARTMENTS D
 ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
 JOIN LOCATIONS L
 ON(D.LOCATION_ID=L.LOCATION_ID)
 JOIN COUNTRIES C
 ON(L.COUNTRY_ID=C.COUNTRY_ID);
 
BEGIN
 FOR I IN EMP_CONTEXT 
 LOOP
  DBMS_OUTPUT.PUT_LINE(I.FIRST_NAME||' '||I.CITY);
 END LOOP;
END;
-------------------------------------------------------------------------

SET SERVEROUTPUT ON
DECLARE
 CURSOR EMP_CONTEXT
 IS 
 SELECT 
BEGIN
END;








